### ISSUE TITLE
Create downloadable libraries to parse and/or convert the GUTMA flight format

### ISSUE THREAD

**Issue by hi-kevin** [interuss/dss#1]
**Is your feature request related to a problem? Please describe.**
Currently, every USS has to write parsers for the GUTMA flight declaration for their own system. The current standard is: https://bitbucket.org/global_utm/flight-declaration-protocol/

**Describe the solution you'd like**
It would be nice to have a parser to read GUTMA format and create objects in the language of the library (like JAVA, C++, Python, Javascript, etc.). Additionally, it would be nice to have a converter from the formats endorsed by the platform (currently NASA's operation format and GUTMA's flight declaration format).

**Describe alternatives you've considered**
This should NOT be a service inside a running InterUSS Platform data node, as it violates the tenet "No details about UAS operations are stored or processed on the InterUSS Platform".

**Additional context**
Comment on this feature request for the languages you think should be supported.

_Remember, to best support collaboration among USSs, there are two key tenets to the InterUSS Platform:
1. The InterUSS Platform is focused on facilitating communication amongst actively operating USSs.
2. No details about UAS operations are stored or processed on the InterUSS Platform. 

Regardless of the new features and changes brought to the platform via the open source process, these two tenets must be enforced to ensure protection of operator and consumer privacy and ensure the competition between USSs for drone services remains intact._

**Comment by hrishiballal** [comment]
This is something that I plan to work on, at the moment, I am planning to incorporate GUTMA flight declaration (both production and development) into InterUSS and then I plan to write converters. I will update the issue here.
