### ISSUE TITLE
Implement versioning API

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/dss#1047]
**Is your feature request related to a problem? Please describe.**
Since a DSS instance is merely a USS system component, versioning the entire USS system would be more straightforward if the InterUSS DSS implementation reported its software version according to a standard API.

**Describe the solution you'd like**
Implement [the InterUSS versioning API](https://github.com/interuss/automated_testing_interfaces/tree/main/versioning) in the InterUSS DSS implementation.

**Describe alternatives you've considered**
The existing [aux API](https://github.com/interuss/dss/blob/ce9e97db6c256c2a6f1d589fcac8cf52d7f7b723/interfaces/aux_/aux_.yaml#L24) does have an existing version endpoint.  In the monitoring repo's [VersionProviderSpecification](https://github.com/interuss/monitoring/blob/69b0cbc76afa29754188d6d2793b8487a11c6a1e/monitoring/uss_qualifier/resources/versioning/client.py#L22), we could add another field named something like `interuss_dss` which would produce a new type of versioning client (perhaps `InterUSSDSSVersionClient`) which would query the existing aux version endpoint.  But, I think that would be backward-looking while transitioning to the standard API would be more forward-looking and encourage USSs to do the same.

**Comment by Shastick** [comment]
Will take a look at this (note: I can't assign myself the issue)

**Comment by Shastick** [comment]
A first proposal is available on #1052: there are some potential things that need discussion (see PR comment for more details)
