### ISSUE TITLE
Ensure transactionality of requests

### ISSUE THREAD

**Issue by steeling** [interuss/dss#116]
Due to CRDB's consistency model, non-causal operations might not appear sequentially https://www.cockroachlabs.com/blog/consistency-model/

To combat this we should place everything in a transaction, including the write subscription, get ISA or write ISA, get subscription flows.

**Comment by BenjaminPelletier** [comment]
Both RID and SCD subsystems now have transactive store interfaces, so I believe this issue is resolved.
