### ISSUE TITLE
Add package description to populate https://godoc.org/github.com/interuss/dss

### ISSUE THREAD

**Issue by vosst** [interuss/dss#138]
More concretely, the following packages need at least a one-line description of their purpose:
- [ ] pkg/dss
- [ ] pkg/dss/auth
- [ ] pkg/dss/build
- [ ] pkg/dss/cockroach
- [ ] pkg/dss/geo
- [ ] pkg/dss/models
- [ ] pkg/dss/validations
- [ ] pkg/errors
- [ ] pkg/logging

**Comment by BenjaminPelletier** [comment]
Resolved by #686
