### ISSUE TITLE
Max subscription limit is not enforced during updates

### ISSUE THREAD

**Issue by steeling** [interuss/dss#160]
Currently updates to an existing subscription can bypass the subscription limit within an area. We should remove the check old == nil https://github.com/interuss/dss/blob/master/pkg/dss/cockroach/subscriptions.go#L257 here. 

This means we'll also have to calculate the difference in s2 cells between the old and the new, and check the subscription count only in the set difference.

**Comment by charlie-pisuraj** [comment]
#169 fixed this issue, I think we can close this now
