### ISSUE TITLE
stacking when setting up

### ISSUE THREAD

**Issue by thura-ntu** [interuss/dss#171]
Hi there,

I'm doing research of "ATM-UTM integration" at NTU (Nanyang Technological University). When I setting up the interuss in my local pc, I am stacking at following. Pls help me to solve.

when I run 

> ~/dss/config/run-locally.sh

![Screenshot from 2019-11-29 12-47-26](https://user-images.githubusercontent.com/58415378/69937173-f1e3f880-1514-11ea-9ff9-56502f4d19cd.png)
 
when I running the docker files

> Error response from daemon: COPY failed: stat /var/lib/docker/tmp/docker-builder052907660/go.mod: no such file or directory

![Screenshot from 2019-12-02 15-04-27](https://user-images.githubusercontent.com/58415378/69937207-0f18c700-1515-11ea-943e-a35a0491542b.png)

Regards,

**Comment by charlie-pisuraj** [comment]
Hi @thura-ntu, I'm unable to reproduce the error you are getting, could you clear your go modcache.
Also the config/run-locally.sh script is used for standing up a local instance of the DSS for manual testing and shouldn't be building anything.

Are you by any chance running the test/docker_e2e.sh?

PS: The run-locally.sh script requires you run it from the repo's root dir. I'll submit a PR so that i can be run from anywhere.

**Comment by thura-ntu** [comment]
Hi @charlie-pisuraj, Thank you for your reply. I'm trying to setup the "Interuss" in my local pc. But I didn't find any instruction to start up the system. So I looking the folder and found "run-locally.sh".

Thanks again for your suggestion to run "test/docker_e2e.sh".

Here is the result


> Re/Create e2e_test_result file
cleaning up any crdb pre-existing containers
Error response from daemon: No such container: dss-crdb-for-debugging
No CRDB to clean up
Starting cockroachdb with admin port on :8080
 -------------- BOOTSTRAP -----------------
Building local container for testing
sha256:4d976dfe58af9c0a06c5eaf53615a3ff6759ce878988338ac627bd4e1bfa124a
 ------------ GRPC BACKEND ----------------
Cleaning up any pre-existing grpc-backend container
Error response from daemon: No such container: grpc-backend-for-testing
No grpc backend to clean up
Starting grpc backend on :8081
185c6a11dfb3b7b6dc4ad04a09895a41b8ded7500a828656fc4104b0a00f6f36
 ------------- HTTP GATEWAY --------------
Cleaning up any pre-existing http-gateway container
Error response from daemon: No such container: http-gateway-for-testing
No http gateway to clean up
Starting http-gateway on :8082
cf7470a28aa203dd840ba165762656899e2a67c239649b396a6fcc2f882eafbb
 -------------- DUMMY OAUTH --------------
Building dummy-oauth server container
sha256:a9a4aada12d004521a7835b58d6897ce02eb3f99f538223961ebed30274d33d3
Cleaning up any pre-existing dummy-oauth container
Error response from daemon: No such container: dummy-oauth-for-testing
No dummy oauth to clean up
Starting mock oauth server on :8085
b9dfd6ab1f2f33830b47d2a0d3badab7d30695bf2dbc86ec4c8cc2f9dbc8534e
 -------------- PYTEST --------------
Building Integration Test container
sha256:2f262fae2187b229698aef22a524ad2b5e967f09b954f2b59ba29500a4b377d7
Finally Begin Testing
============================= test session starts ==============================
platform linux -- Python 3.7.5, pytest-4.4.1, py-1.8.0, pluggy-0.13.1 -- /usr/local/bin/python
cachedir: .pytest_cache
rootdir: /app
collecting ... collected 55 items
test_isa_expiry.py::test_create PASSED                                   [  1%]
test_isa_expiry.py::test_valid_immediately PASSED                        [  3%]
test_isa_expiry.py::test_sleep_5_seconds PASSED                          [  5%]
test_isa_expiry.py::test_not_returned_by_id PASSED                       [  7%]
test_isa_expiry.py::test_not_returned_by_search PASSED                   [  9%]
test_isa_simple.py::test_isa_does_not_exist PASSED                       [ 10%]
test_isa_simple.py::test_create_isa PASSED                               [ 12%]
test_isa_simple.py::test_get_isa_by_id PASSED                            [ 14%]
test_isa_simple.py::test_get_isa_by_search_missing_params PASSED         [ 16%]
test_isa_simple.py::test_get_isa_by_search PASSED                        [ 18%]
test_isa_simple.py::test_get_isa_by_search_earliest_time_included PASSED [ 20%]
test_isa_simple.py::test_get_isa_by_search_earliest_time_excluded PASSED [ 21%]
test_isa_simple.py::test_get_isa_by_search_latest_time_included PASSED   [ 23%]
test_isa_simple.py::test_get_isa_by_search_latest_time_excluded PASSED   [ 25%]
test_isa_simple.py::test_get_isa_by_search_area_only PASSED              [ 27%]
test_isa_simple.py::test_get_isa_by_search_huge_area PASSED              [ 29%]
test_isa_simple.py::test_delete_isa_wrong_version PASSED                 [ 30%]
test_isa_simple.py::test_delete_isa_empty_version PASSED                 [ 32%]
test_isa_simple.py::test_delete_isa PASSED                               [ 34%]
test_isa_simple.py::test_get_deleted_isa_by_id PASSED                    [ 36%]
test_isa_simple.py::test_get_deleted_isa_by_search PASSED                [ 38%]
test_isa_validation.py::test_isa_huge_area PASSED                        [ 40%]
test_isa_validation.py::test_isa_empty_vertices PASSED                   [ 41%]
test_isa_validation.py::test_isa_missing_footprint PASSED                [ 43%]
test_isa_validation.py::test_isa_missing_spatial_volume PASSED           [ 45%]
test_isa_validation.py::test_isa_missing_extents PASSED                  [ 47%]
test_isa_validation.py::test_isa_start_time_in_past PASSED               [ 49%]
test_isa_validation.py::test_isa_start_time_after_time_end PASSED        [ 50%]
test_isa_validation.py::test_isa_not_on_earth PASSED                     [ 52%]
test_subscription_isa_interactions.py::test_create_isa PASSED            [ 54%]
test_subscription_isa_interactions.py::test_create_subscription PASSED   [ 56%]
test_subscription_isa_interactions.py::test_modify_isa PASSED            [ 58%]
test_subscription_isa_interactions.py::test_delete_isa PASSED            [ 60%]
test_subscription_isa_interactions.py::test_delete_subscription PASSED   [ 61%]
test_subscription_simple.py::test_sub_does_not_exist PASSED              [ 63%]
test_subscription_simple.py::test_create_sub PASSED                      [ 65%]
test_subscription_simple.py::test_get_sub_by_id PASSED                   [ 67%]
test_subscription_simple.py::test_get_sub_by_search PASSED               [ 69%]
test_subscription_simple.py::test_get_sub_by_searching_huge_area PASSED  [ 70%]
test_subscription_simple.py::test_delete_sub_empty_version PASSED        [ 72%]
test_subscription_simple.py::test_delete_sub_wrong_version PASSED        [ 74%]
test_subscription_simple.py::test_delete_sub PASSED                      [ 76%]
test_subscription_simple.py::test_get_deleted_sub_by_id PASSED           [ 78%]
test_subscription_simple.py::test_get_deleted_sub_by_search PASSED       [ 80%]
test_subscription_validation.py::test_create_sub_empty_vertices PASSED   [ 81%]
test_subscription_validation.py::test_create_sub_missing_footprint PASSED [ 83%]
test_subscription_validation.py::test_create_sub_with_huge_area PASSED   [ 85%]
test_subscription_validation.py::test_create_too_many_subs PASSED        [ 87%]
test_subscription_validation.py::test_create_sub_with_too_long_end_time PASSED [ 89%]
test_subscription_validation.py::test_update_sub_with_too_long_end_time PASSED [ 90%]
test_token_validation.py::test_put_isa_with_read_only_scope_token PASSED [ 92%]
test_token_validation.py::test_create_isa PASSED                         [ 94%]
test_token_validation.py::test_get_isa_without_token PASSED              [ 96%]
test_token_validation.py::test_get_isa_with_fake_token PASSED            [ 98%]
test_token_validation.py::test_get_isa_without_scope PASSED              [100%]
--------------------- generated xml file: /app/test_result ---------------------
========================== 55 passed in 10.24 seconds ==========================
./test/docker_e2e.sh: line 99: http-gateway-for-testing.log: Permission denied
 
after running "test/docker_e2e.sh", I found 3 containers.

> CONTAINER ID        IMAGE                      COMMAND                  CREATED              STATUS              PORTS                    NAMES
b9dfd6ab1f2f        local-dummy-oauth          "/usr/bin/dummy-oaut…"   About a minute ago   Up About a minute   0.0.0.0:8085->8085/tcp   dummy-oauth-for-testing
cf7470a28aa2        local-interuss-dss-image   "http-gateway -grpc-…"   About a minute ago   Up About a minute   0.0.0.0:8082->8082/tcp   http-gateway-for-testing
185c6a11dfb3        local-interuss-dss-image   "grpc-backend --cock…"   About a minute ago   Up About a minute                            grpc-backend-for-testing



Kindly, please help to setup the "Interuss" in my local pc. 

Regards,

**Comment by charlie-pisuraj** [comment]
Hi @thura-ntu, so running the docker_e2e.sh proved that things are building just fine and can execute correctly. I recently made a change to run-locally.sh with a message to tell the user when everything is ready. if you can pull again and re run the `run-locally.sh` script and let me know if there is any more confusion.

Also please take a look at this to see all the end points available.
https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/BenjaminPelletier/DiscoveryAndSynchronization/rid/api/dss.yaml#tag/dss

**Comment by thura-ntu** [comment]
Hi @charlie-pisuraj, thanks for helping me. after pulling and run new "run-locally.sh", it is working fine. 

I browse "http://localhost:8085/token", I got the token key. and when I placed the token at postman and send, I got following error.
![Screenshot from 2019-12-05 15-04-07](https://user-images.githubusercontent.com/58415378/70211720-bfced280-1770-11ea-8fd3-1be90e3c0a6c.png)

Please help me. 

Thanks,

**Comment by charlie-pisuraj** [comment]
That is the correct response as the token you have is invalid due to missing fields when requesting it. Please take a look at the logs, as well as the tests to see what fields are necessary for obtaining a valid token.

**Comment by thura-ntu** [comment]
Hi @charlie-pisuraj, Thank you for your reply. When I check the log, I found 

> token validation failed	{"error": "Missing Issuer URI"}

I tried as follow, but still getting "invalid".
![Screenshot from 2019-12-05 18-25-01](https://user-images.githubusercontent.com/58415378/70226891-99b72b80-178c-11ea-980e-38d1756e0849.png)

Can you help to explain a bit more? I'm really nervous. 

Thanks,

**Comment by BenjaminPelletier** [comment]
This is a currently-undocumented feature of the dummy-oauth provider -- when requesting a token, include an `issuer=localhost` parameter so that the `iss` field of the JWT token is populated.  This should result in a token that the DSS will accept -- the root issue indicated by the "Missing Issuer URI" error message (which we will propagate to the client in #176) is that the JWT access token does not have an `iss` field, and so is therefore considered invalid.

With any other invalid token errors in the future, it would be valuable to also post the token content (which can be examined with https://jwt.io) as long as the token is not for a real/production system.

**Comment by thura-ntu** [comment]
Hi @BenjaminPelletier, Thanks for your comment. I got following when I run the "check_dss.sh". 

> DSS response to Mauna Loa ISA query:
=============
{
  "service_areas": [
  ]
}
=============
See https://tiny.cc/dssapi_rid for a more complete DSS API description.

And I think I need to wait until the proper document come out.


Thanks,

**Comment by BenjaminPelletier** [comment]
Great, it looks like you have a functioning InterUSS DSS instance!  The [OpenAPI specification](https://tiny.cc/dssapi_rid) (which is included as a [submodule in this project](https://github.com/interuss/dss/tree/master/interfaces/uastech)) is a comprehensive description of the APIs exposed by the DSS.  We do not yet have a document that conceptually describes the expectations and information flow for remote ID; the best source for this currently is the [ASTM remote ID standard](https://www.astm.org/DATABASE.CART/WORKITEMS/WK65041.htm).  Is that the kind of document you had in mind?

**Comment by thura-ntu** [comment]
Hi @BenjaminPelletier, Thanks for your reply. I already checked "OpenAPI specification" doc. Currently, I'm investigating "How to interoperate with our UTM and other uss". So, I need the interuss system properly run in my local PC and need to understand inter-active with other uss/utm and ATM systems.

Thanks,

**Comment by BenjaminPelletier** [comment]
While we do plan to create some overview documentation for how ASTM-compliant remote ID and strategic deconfliction work (or might work, for aspects that haven't been fully-developed), this repository is primarily just an implementation of that standard and not the standard itself.  It sounds like the standard itself is what would be most helpful to read.  In the mean time, perhaps PR #182 might be helpful (preview currently available [here](https://github.com/BenjaminPelletier/dss/blob/feature/conceptual_docs/concepts.md)).

**Comment by BenjaminPelletier** [comment]
The codebase has advanced substantially since this issue and I think many improvements in the code and documentation should render this issue obsolete.  Feel free to re-open if that is not the case.
