### ISSUE TITLE
Create downloadable libraries to parse and/or convert the NASA operation format 

### ISSUE THREAD

**Issue by hi-kevin** [interuss/dss#2]
**Is your feature request related to a problem? Please describe.**
Currently, every USS has to write parsers for the NASA operation for their own system. The current standard is v3: https://app.swaggerhub.com/apis/utm/uss/v3#/A._Required_Endpoints/get_operations, but is moving to v4: https://app.swaggerhub.com/apis/utm/uss/v4#/A.%20Required%20Endpoints/get_operations

**Describe the solution you'd like**
It would be nice to have a parser to read NASA format and create objects in the language of the library (like JAVA, C++, Python, Javascript, etc.). Additionally, it would be nice to have a converter from the formats endorsed by the platform (currently NASA's operation format and GUTMA's flight declaration format).

**Describe alternatives you've considered**
This should NOT be a service inside a running InterUSS Platform data node, as it violates the tenet "No details about UAS operations are stored or processed on the InterUSS Platform".

**Additional context**
Comment on this feature request for the languages you think should be supported.

_Remember, to best support collaboration among USSs, there are two key tenets to the InterUSS Platform:
1. The InterUSS Platform is focused on facilitating communication amongst actively operating USSs.
2. No details about UAS operations are stored or processed on the InterUSS Platform. 

Regardless of the new features and changes brought to the platform via the open source process, these two tenets must be enforced to ensure protection of operator and consumer privacy and ensure the competition between USSs for drone services remains intact._

**Comment by issmith1** [comment]
>>nice to have a converter 
Do you mean convert NASA format to slippy 'coords' csv list, as well as GridCellOperation?

**Comment by hi-kevin** [comment]
This was meant to convert NASA format into a usable object in a USS's preferred language, perhaps with tools for validation, visualization, etc. Or even transforming into other standards. Above and beyond the code you can automatically create from swaggerhub/github yamls.
