### ISSUE TITLE
Not all status codes in storage_interface.py can be returned by Flask

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/dss#20]
Flask's abort method only recognizes some of the HTTP codes, and storage_interface.py uses codes that abort does not recognize.  When one of these unrecognized codes is passed to abort, it causes an HTTP 500 due to a LookupError in werkzeug.  HTTP 424 should be replaced as a return code in storage_interface.py.

**Comment by hrishiballal** [comment]
According to Flask API spec the closest one that I can see is [HTTP 412](https://www.flaskapi.org/api-guide/status-codes/) "Precondition failed". Would that work? I can make a PR to return 412 with a note that it is really 424.

**Comment by hi-kevin** [comment]
Actually, this issue should revamp the storage_interface error handling. It currently uses HTTP codes but should have it's own enum, and the API lauerr should decide how this maps to http codes. There is a TODO in the storage interface already. Let's use this issue to do it properly.

**Comment by hi-kevin** [comment]
This has been patched in the TCL4 branch. This issue will remain open to create an error enum for storage_interface and update the API to match enum to HTTP error codes that Flask supports.
