### ISSUE TITLE
tcl4 branch permits operators to declare operations outside of their operational time window

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/dss#21]
When issuing a PUT to GridCellOperator/z/x/y, a client may specify one or more operations with effective_time_begin and effective_time_end that are outside the operator's minimum_operation_timestamp and maximum_operation_timestamp.  The InterUSS Platform should probably automatically expand an operators minimum and maximum operation_timestamps to enclose all effective_time begin and end for all operations during a PUT to this endpoint or an operation endpoint.

**Comment by issmith1** [comment]
>>automatically expand
did you consider strict validation and reject?  In UTM this is the pattern thru out; sender makes it right.
