### ISSUE TITLE
Use one DB connection for both scd and rid

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/dss#261]
It might be nice to allow the caller to use one connection for both scd and rid. We could do something like have a Store.WithDB() or something

_Originally posted by @steeling in https://github.com/interuss/dss/pull/260_

**Comment by vosst** [comment]
I think this one is done, closing out.

**Comment by nasajoey** [comment]
There is no visible context for the acronym "SCD"... just taking a guess that it stands for "Strategic Conflict Detection" or something like that?  Is this terminology documented somewhere?  I might have just missed it.  Thanks.

**Comment by nasajack** [comment]
While documenting the DSS on our side, I also tried to find the meaning of the acronym "SCD" and found this page. After doing some investigations, Joey's "Strategic Conflict Detection" is mentioned in ASTM F3548-21 scope: https://www.astm.org/f3548-21.html

The scope also mentioned "Strategic Coordination" and "Strategic Deconfliction." I am wondering if SCD could mean "Strategic Coordination and Deconfliction."

In addition, it looks like SCD could also mean "Strategic Conflict Deflection" based on the latest InterUSS site: https://interussplatform.org/strategic-conflict-deflection/ -- but this site was first available in mid-2022 according to the Internet Archive, while Joey was asking the question back to mid-2020.

**Comment by nasajoey** [comment]
Hi Jack!  I searched the standard itself, and the most reasonable definition is here:

> 5.1.1.3 SCDxxxx – requirements specific to Strategic Conflict Detection

The term "Strategic Conflict Detection" is used throughout the standard as well as the acronym "SCD" but the connection between them is inferred other than the above quoted definition for the requirements numbering.  I think it is an oversight that it is missing from section "3.3 Acronyms and Abbreviations."

They don't define the acronym elsewhere that I can see.  I'm guessing the InterUSS website URL you noted is an unfortunate typo.

**Comment by BenjaminPelletier** [comment]
When documenting, it's probably useful to separate the DSS concept and requirements (established by ASTM F3411-19, F3411-22a, and F3548-21) from InterUSS's implementation (conceivably one of many, though I do not know of any other public implementations) which should satisfy the requirements of all three of these standards.  There are really 3 DSSs: the F3411-19 one, the F3411-22a one, and the F3548-21 one; it just happens to be the case that this InterUSS repository provides implementations of all three in a single binary.

The "scd" abbreviation in this repo (the InterUSS implementation of all three DSS concepts) is due to the fact that F3548-21 has poor naming.  On the one hand, the official name of F3548-21 involves "UTM".  On the other hand, the most common understanding of "UTM" is broader than just the stuff in F3548-21; for instance, many people would include network remote identification in the UTM bucket.  InterUSS wanted an abbreviation to refer to the functionality supporting the requirements of F3548-21, but this abbreviation was chosen substantially before publication, and before F3548-21 content was finalized.  It was thought at the time that "utm" was not a good abbreviation to choose for the above reason.  "scd" was chosen instead.  This too was a suboptimal choice as a specific service within F3548-21 was specifically named "strategic conflict detection" in the final version of the standard, so it is confusing for "scd" in this repository to refer to "all the functionality in F3548-21", but optimal naming of internal components has not been the highest priority for InterUSS to address.
