### ISSUE TITLE
invalid times should return 4xx's

### ISSUE THREAD

**Issue by steeling** [interuss/dss#275]
currently it is possible to hit this database level constraint:
CHECK (starts_at IS NULL OR ends_at IS NULL OR starts_at < ends_at)

which results in a 500. We should check this in code and return a 4xx level error

**Comment by BenjaminPelletier** [comment]
This may have been addressed in #360, but we should add prober tests to validate that invalid (or missing) times return 400.

**Comment by pratibhagupta2109** [comment]
Fixed in #558
