### ISSUE TITLE
Add endpoint to print currently-running version

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/dss#342]
To help troubleshoot issues with DSS instances deployed by others, it would be helpful to have an endpoint that printed basic version information of the currently-running binary.  Perhaps the git commit ID + if anything was modified locally, a hash of the binary, or something similar.  Manually incrementing a content-based version ID will probably not work in a reliable workflow.

**Comment by vosst** [comment]
I think we want semantic versioning (ideally corresponding to tags) and the short hash of the relevant git commit, e.g.:
```
1.2.5-b454b5d
```
If an image/executable has been built from a commit with local and uncommitted modifications, we would add an additional suffix `-dirty`.

@BenjaminPelletier makes sense?

**Comment by BenjaminPelletier** [comment]
Yep, that sounds great to me.
