### ISSUE TITLE
DSS leaking OVNs

### ISSUE THREAD

**Issue by nasajoey** [interuss/dss#347]
**Describe the bug**
On PUT to operation_references, OVNs not owned by the PUTting USS can be leaked.

**To Reproduce**
1. USS1 successfully submits operation to a clean DSS.
2. USS2 submits intersecting operation
3. USS2 receives 409 and array of entity_conflicts
4. entity_conflicts contains USS1's operation along with its OVN

**Expected behavior**
Given I submit an operation
And the operation intersects with Operation Z with OVN 123 in DSS
And I did not provide OVN 123 for Operation Z
When I receive the response from the DSS
Then the response is HTTP 409
And the response contains an entity_conflicts array with Operation Z
And the data for Operation Z **does NOT** contain its OVN

**Additional context**
@arkits tracked down this bug, all glory be to him.  He even found the place to fix it:

See [operations_handler.go lines 158-160](https://github.com/interuss/dss/blob/b454b5d35e065d2bdf2b8db62450ff7d8885a6d7/pkg/scd/operations_handler.go#L158) for the query handler where OVNs are removed if the owner did not make the request:
```
if op.Owner != owner {
	p.Ovn = ""
}
```
A block like that is missing from the PUT handler somewhere around line 300 of the same file.

**Comment by vosst** [comment]
@nasajoey @arkits thanks for the detailed bug report. Given that you already identified a fix, do you want to go ahead and put up a PR? If not, I'm happy to help out.

**Comment by nasajoey** [comment]
I have concerns with NASA contributing code.  Would prefer to not open that can at this time.

**Comment by vosst** [comment]
Sounds good, I'll take care of the change then.
