### ISSUE TITLE
Support localhost URL when testing in dev mode

### ISSUE THREAD

**Issue by clymeraa** [interuss/dss#371]
Run both DSS on Docker and test PSU together on localhost.  Attempt to do a PUT operation reference to the DSS with http://localhost as uss_url_base address.  This will return the error 'uss_base_url in new_subscription must use TLS.' 

It is desired for developers to be able to test with the DSS and a PSU running locally. Typically for this testing we are running the DSS in dev mode.  Is it possible to relax that check in dev mode to support this kind of testing?

**Comment by BenjaminPelletier** [comment]
This should be resolved by #548
