### ISSUE TITLE
`run_locally.sh` does not rebuild when new commits are pulled

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/dss#384]
**Describe the bug**
When attempting to deploy a local instance of a new version of the DSS codebase `run_locally.sh` does not always automatically rebuild the DSS image.

**To Reproduce**
To deploy a local instance of a new version of the DSS codebase, one would generally:
```shell script
run_locally.sh down
git pull
run_locally.sh
```

**Expected behavior**
The new DSS instance should incorporate the changes acquired with `git pull`.

**Actual behavior**
The new DSS instance does not include changes acquired with `git pull`.

**Workaround**
Explicitly rebuilding fixes the problem:
```shell script
run_locally.sh down
git pull
run_locally.sh build
run_locally.sh
```

**Suggested fix**
We should modify run_locally.sh as needed to automatically rebuild images when they are out of date.

**Alternative**
We could indicate to the user the commit off of which the current images were built when `run_locally.sh` is invoked.

**Comment by pratibhagupta2109** [comment]
fixed in #584
