### ISSUE TITLE
SCD Subscriptions do not track DependentOperations

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/dss#386]
Each Operation is required to be covered by a Subscription.  This requirement can be fulfilled by either providing the necessary information to simultaneously create a new (implicit) Subscription along with the Operation, or by providing the ID of an existing Subscription that covers the Operation.  Either way, the Operation becomes dependent on the Subscription, so it becomes invalid to shrink the Subscription spacetime area in a way that would exclude any part of the Operation, or to delete the Subscription entirely.  We should track these dependences with a Subscription's DependentOperations.  However, currently, we do not validate against DependentOperations when mutating or deleting a Subscription -- those checks must be added.

**Comment by BenjaminPelletier** [comment]
More importantly, the SCD database schema does not even include dependent Operations for Subscriptions; this column needs to be added.

**Comment by aegisbing8611** [comment]
https://github.com/interuss/dss/pull/452
aims to resolve this and is being reviewed

**Comment by BenjaminPelletier** [comment]
We need to uncomment text in monitoring.prober.scd.test_operations_simple that refers to this bug

**Comment by pratibhagupta2109** [comment]
Test cases updated in #580.
