### ISSUE TITLE
Add flag to allow http URLs

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/dss#404]
SCD currently rejects requests using http:// URLs (rather than https://).  While that is required in production by the standard, it would be useful to test functionality with plain http URLs.  We should add a flag to enable http URLs and make sure it is available in the relevant configurations (though probably not the Tanka/Kubernetes configuration because there probably wouldn't be a use case for a full deployment to accept http URLs).

**Comment by vosst** [comment]
To be precise: Is this behavior observed with the 'raw' `http-gateway` executable or only with routing/load-balancing in place?

**Comment by BenjaminPelletier** [comment]
Fixed by #548
