### ISSUE TITLE
Add confirmation to make_certs.py when overwriting existing certs

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/dss#413]
Currently, `make-certs.py` will happily overwrite existing data without prompting the user even though that is rarely the right thing to do.  We should add a user prompt when existing certs would be overwritten to ask if that's really what the user wants to do, and perhaps a brief explanation of when make-certs.py should be used (only when creating a new cluster for the first time, in general).

**Comment by pratibhagupta2109** [comment]
Isn't `keep_ca_cert` at https://github.com/interuss/dss/blob/master/build/make-certs.py#L66 doing the same thing?

**Comment by BenjaminPelletier** [comment]
Resolved by #664
