### ISSUE TITLE
SCD - Transient Http 500 Error when concurrently create/mutate/delete operations that have volume cover different 2d areas

### ISSUE THREAD

**Issue by aegisbing8611** [interuss/dss#421]
Currently when we concurrently create/mutate/delete operations that have non-overlapping geospatial areas (> 11 km away from each other), once in a while (1 out of 10 test runs) we observed the transient http 500 error.

```
>       assert resp.status_code == 200, resp.content
E       AssertionError: b'{
E           "error": "Internal server error E:851df5e0-dee4-46c6-93d4-6be66ed7efc4",
E           "code": 13,
E           "message": "Internal server error E:851df5e0-dee4-46c6-93d4-6be66ed7efc4",
E           "error_id": "E:ba9cd948-d307-485c-9a90-f78bd684b801"
E         }'
E       assert 500 == 200
```

Detailed trace:

local-dss-grpc-backend_1      | 2020-08-26T23:43:43.363Z	error	errors/errors.go:145	Uncoded error E:851df5e0-dee4-46c6-93d4-6be66ed7efc4 during unary server call	{"method": "/scdpb.UTMAPIUSSDSSAndUSSUSSService/PutOperationReference", "stacktrace": "Unable to SearchOperations\n --- at /app/pkg/scd/operations_handler.go:413 (Server.PutOperationReference.func1) ---\nCaused by: Error fetching Operations\n --- at /app/pkg/scd/store/cockroach/operations.go:296 (repo.searchOperations) ---\nCaused by: Error in query: \n\t\t\tSELECT\n\t\t\t\tscd_operations.id,scd_operations.owner,scd_operations.version,scd_operations.url,scd_operations.altitude_lower,scd_operations.altitude_upper,scd_operations.starts_at,scd_operations.ends_at,scd_operations.subscription_id,scd_operations.updated_at\n\t\t\tFROM\n\t\t\t\tscd_operations\n\t\t\tJOIN\n\t\t\t\t(SELECT DISTINCT\n\t\t\t\t\tscd_cells_operations.operation_id\n\t\t\t\tFROM\n\t\t\t\t\tscd_cells_operations\n\t\t\t\tWHERE\n\t\t\t\t\tscd_cells_operations.cell_id = ANY($1)\n\t\t\t\t)\n\t\t\tAS\n\t\t\t\tunique_operations\n\t\t\tON\n\t\t\t\tscd_operations.id = unique_operations.operation_id\n\t\t\tWHERE\n\t\t\t\tCOALESCE(scd_operations.altitude_upper >= $2, true)\n\t\t\tAND\n\t\t\t\tCOALESCE(scd_operations.altitude_lower <= $3, true)\n\t\t\tAND\n\t\t\t\tCOALESCE(scd_operations.ends_at >= $4, true)\n\t\t\tAND\n\t\t\t\tCOALESCE(scd_operations.starts_at <= $5, true)\n --- at /app/pkg/scd/store/cockroach/operations.go:53 (repo.fetchOperations) ---\nCaused by: pq: restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_PUSHER_ABORTED): \"sql txn\" meta={id=c618449f key=/Table/57/1/\"\\xa2[z\\x9f\\x00\\xa6AǢJ0\\x84H\\x85\\xdbK\"/0 pri=0.00824495 epo=1 ts=1598485422.915052750,1 min=1598485422.907485326,0 seq=4} lock=true stat=ABORTED rts=1598485422.915052750,1 wto=false max=1598485422.907485326,0", "error": "pq: restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_PUSHER_ABORTED): \"sql txn\" meta={id=c618449f key=/Table/57/1/\"\\xa2[z\\x9f\\x00\\xa6AǢJ0\\x84H\\x85\\xdbK\"/0 pri=0.00824495 epo=1 ts=1598485422.915052750,1 min=1598485422.907485326,0 seq=4} lock=true stat=ABORTED rts=1598485422.915052750,1 wto=false max=1598485422.907485326,0"}

**Comment by vosst** [comment]
Most of these issues can be tracked back to transaction retries not working properly due to: 
 * https://github.com/interuss/dss/commit/ba3077915e8a32a0d9bc827ad7e4723a320ef41d
 * https://github.com/interuss/dss/commit/c6391e97ad0dc4ba0000c84ac67e19f1270876dd
Wrapping the original errors results in https://github.com/cockroachdb/cockroach-go/blob/master/crdb/tx.go#L185 returning `false` even if the original error is retry-able.

Nevertheless, your work on a test case is very much appreciated and should help with preventing regressions going forward. I'll handle the fix to the error reporting, aiming to propose an extension to the upstream `crdb` library to optionally unwrap errors.

**Comment by vosst** [comment]
With https://github.com/palantir/stacktrace/pull/14/files, the cockroach client-side retry library will do the right thing.

**Comment by aegisbing8611** [comment]
Np, thanks @vosst for sharing me more context!

**Comment by pratibhagupta2109** [comment]
create/mutate/delete operations are tested with different 2D areas as per this [code](https://github.com/interuss/dss/blob/master/monitoring/prober/scd/test_operation_simple_heavy_traffic_concurrent.py#L60). Unit tests are passing successfully.
