### ISSUE TITLE
Garbage collector functionality remove expired data after x period.

### ISSUE THREAD

**Issue by Dos-Ph** [interuss/dss#423]
Set up scheduler using Go Job Scheduler -> https://golangexample.com/go-job-scheduler-for-humans/

Changes:
1. Add 'deleteExpiredRecords(ctx, duration, writer)' function to ISA interface (dss/pkg/rid/repos/isa.go) and Subscription interface (dss/pkg/rid/repos/subscription.go). Talked to Charlie, he said 30 mins should be enough for an expired duration.

2. Implement the 'deleteExpiredRecords' function in dss/pkg/rid/store/cockroach/identification_service_area.go and dss/pkg/rid/store/cockroach/subscription.go
- sql: DELETE FROM identification_service_areas WHERE ends_at < dateadd(minute, -30, GetDate()) and writer = '<writer>'.
- sql: DELETE FROM subscriptions WHERE ends_at < dateadd(minute, -30, GetDate()) and writer = '<writer>'.
- log only when error occur

3. Create Garbage collector class
- File path: dss/pkg/rid/store/garbage_collector.go
- deleteExpiredRecords(ctx, duration, writer) function: delete expired records from the table after they expire for x minutes. The function call deleteExpiredRecords function in identification_service_area.go and subscription.go.

4. Setup scheduler in main.go when we create server by creating Garbage collector class and setting up a schedule to call it every 1 hour(?).
https://github.com/interuss/dss/blob/23465ba1c47b51f74ecf67b7624dccc64f65460a/cmds/grpc-backend/main.go#L245

Alternative1:
Instead of having a 'deleteExpiredRecords' function, we have 'listExpiredRecords' function. The function returns record obj and call DeleteSubscription and [DeleteISA](https://github.com/interuss/dss/blob/23465ba1c47b51f74ecf67b7624dccc64f65460a/pkg/rid/store/cockroach/identification_service_area.go#L184) function. 

Alternative2:
Instead of having separate 'deleteExpiredRecords' functions for ISA and Subscription, we have only one private function in Garbage collector class which gets table name as an input. 
- sql: DELETE FROM<tablename> WHERE ends_at < dateadd(minute, -30, GetDate()) and writer = '<writer>'.
For this one, we don't need to make a change on the ISA/Subscription interface. The function will be implemented as a private class in the Garbage collector class.

**Comment by charlie-pisuraj** [comment]
@vosst @BenjaminPelletier , thoughts?

**Comment by BenjaminPelletier** [comment]
I think the garbage issue will be present for all repo implementations, so I think the proposal and Alternative1 are better than Alternative2.  I think I'm largely indifferent between the proposal and Alternative1 with a slight preference toward Alternative1 because that will test more of the code paths with a mocked repo.  It seems like the SQL statement should also allow writer=<identity of server>, right?  Otherwise, how do entries with non-null writer get deleted?

**Comment by Dos-Ph** [comment]
> I think the garbage issue will be present for all repo implementations, so I think the proposal and Alternative1 are better than Alternative2. I think I'm largely indifferent between the proposal and Alternative1 with a slight preference toward Alternative1 because that will test more of the code paths with a mocked repo. It seems like the SQL statement should also allow writer=, right? Otherwise, how do entries with non-null writer get deleted?

Oh, that is a good point! @charlie-pisuraj Can process delete records that it doesn't own?

**Comment by charlie-pisuraj** [comment]
Yeah theoretically we would need to manually garbage collect just once then the system should take over. But I understand that other DSS might not have GC enabled to begin with.

**Comment by BenjaminPelletier** [comment]
The garbage collector for orphaned ISAs is implemented.
