### ISSUE TITLE
Some loop validation failures result in 500 rather than 400

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/dss#460]
Example: the following call produces a 500 rather than a 400:

https://DSS/v1/dss/subscriptions?area=-80.75088500976562,37.045312802603355,-80.2496337890625,37.045312802603355,-80.2496337890625,37.35487607348372,-80.75088500976562,37.35487607348372,-80.75088500976562,37.045312802603355

**Comment by pratibhagupta2109** [comment]
Fixed in #556
