### ISSUE TITLE
DSS returns 200 even when operation reference is created the first time

### ISSUE THREAD

**Issue by MAbr53** [interuss/dss#462]
According to ASTM specs, DSS must return 200 when operation reference is updated, but it must return 201 when new operation reference is created. In fact, it always returns 200, even when operation reference is created the first time.

Found while testing for UAMX3-582. To reproduce in UAMX3-582 branch:

1. Start: operator-api, conformance-checker, datastore, fims-az-sig, dc-submitter, jaegertracing, tokenprovider, postgres, and interuss-local/dss in a docker
2. Run systest: ./run.sh dockerized gov.nasa.nup.NupBasicTest.testSuccessfulOperationLifecycle
3. Examine the operator-api log-file. You can also inspect jagger traces for PsuExchangeUtils.send that clearly show "actual_http_response": 200 in psuExchangeBody log.

**Comment by BenjaminPelletier** [comment]
Fixed by #905
