### ISSUE TITLE
DSS does not validate USS URL for subscriptions

### ISSUE THREAD

**Issue by clymeraa** [interuss/dss#468]
**Describe the bug**
When an operation is created with the DSS, the baseURL is verified to be an https address.  This same check is not performed for subscriptions or constraints, but probably should be. 

**To Reproduce**
1. Create a subscription with the DSS. Provide an "http" baseURL. 
2. Subscription is accepted. 
**Expected behavior**
Subscription should have been rejected.

**Comment by BenjaminPelletier** [comment]
This should be addressed by #540

**Comment by BenjaminPelletier** [comment]
Similar issues with other resource types should be addressed by #548.
