### ISSUE TITLE
Prober test fails when run by different user

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/dss#472]
When the prober test suite is run by one client ID, it then cannot be run (successfully) by a different client ID; there are two failures apparently due to resources that are not cleaned up.

**Comment by BenjaminPelletier** [comment]
#489 addresses a large part of this bug.  We should also make resource IDs dependent on calling USS so that two USSs aren't trying to use the same resource ID.

**Comment by pratibhagupta2109** [comment]
fixed in #549
