### ISSUE TITLE
Add script to run integration test on local DSS instance

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/dss#490]
Currently, we have `docker_e2e.sh` which brings up an ephemeral DSS instance, runs the `prober` integration test on it, and then tears everything down.  We also have the `run_locally.sh` tool which brings up a persistent local DSS instance.  But, we do not have a simple way of running the `prober` integration test on a persistent local DSS instance.  We should add a `probe_local_instance.sh` script that performs the testing portion of `docker_e2e.sh` on the DSS instance brought up by `run_locally.sh`.

To do this, first we should instruct the local DSS instance to accept tokens addressed to a couple hosts other than `localhost` by changing the appropriate two lines in the `grpc_backend.sh` startup script to be `-accepted_jwt_audiences localhost,local-gateway,dss_sandbox_local-dss-http-gateway_1 \`.  Then, the `probe_local_instance.sh` script can look something like this:

```bash
docker build -q --rm -f monitoring/prober/Dockerfile monitoring -t e2e-test

docker run --network dss_sandbox_default \
  --link dss_sandbox_local-dss-dummy-oauth_1:oauth \
	--link dss_sandbox_local-dss-http-gateway_1:local-gateway \
	-v "${RESULTFILE}:/app/test_result" \
	e2e-test \
	"${1:-.}" \
	--junitxml=/app/test_result \
	--dss-endpoint http://local-gateway:8082 \
	--rid-auth "DummyOAuth(http://oauth:8085/token,sub=fake_uss)" \
	--scd-auth1 "DummyOAuth(http://oauth:8085/token,sub=fake_uss)" \
	--scd-auth2 "DummyOAuth(http://oauth:8085/token,sub=fake_uss2)"
```

It would be good to also include the smart logic in `docker_e2e.sh` that allows the script to be run successfully even if the user is not in quite the right working directory.

**Comment by pratibhagupta2109** [comment]
Fixed in PR #492.
