### ISSUE TITLE
Incorrect error code for `delete` method on `operational_intent_references` endpoint

### ISSUE THREAD

**Issue by svishnu-flyanra** [interuss/dss#575]
When you run the current version of the `test_op_repeated_requests_v15` test in the [`monitoring/prober/scd/test_operation_references_error_cases.py`](https://github.com/interuss/dss/blob/73470c455c3bf3fc759d842c542743b8e8e116bb/monitoring/prober/scd/test_operation_references_error_cases.py#L389) file the delete method you get a `405` error when you don't provide an `ovn` this is incorrect. 

According to the spec it should be a ~~`409`~~ `400`.

**Comment by BenjaminPelletier** [comment]
The API defines [GET](https://github.com/astm-utm/Protocol/blob/f6e5ee5a84cbe56d1b39187aa5ba0f67a7d8f5ec/utm.yaml#L2072) and [PUT](https://github.com/astm-utm/Protocol/blob/f6e5ee5a84cbe56d1b39187aa5ba0f67a7d8f5ec/utm.yaml#L2123) for [`/operational_intent_references/{entity_id}`](https://github.com/astm-utm/Protocol/blob/f6e5ee5a84cbe56d1b39187aa5ba0f67a7d8f5ec/utm.yaml#L2061) but not DELETE, so this seems like an appropriate error code.  Probably the test should be using [`/operational_intent_references/{entity_id}/{ovn}`](https://github.com/astm-utm/Protocol/blob/f6e5ee5a84cbe56d1b39187aa5ba0f67a7d8f5ec/utm.yaml#L2201)

**Comment by svishnu-flyanra** [comment]
But isn't [this](https://github.com/astm-utm/Protocol/blob/f6e5ee5a84cbe56d1b39187aa5ba0f67a7d8f5ec/utm.yaml#L2296) this a `DELETE` for `opreational_intent_references`? 
Moreover, based on the error [400 doc](https://github.com/astm-utm/Protocol/blob/f6e5ee5a84cbe56d1b39187aa5ba0f67a7d8f5ec/utm.yaml#L2315) shouldn't a missing `ovn` (which is a parameter) result in a `400`?

**Comment by svishnu-flyanra** [comment]
Also, using the `/operational_intent_references/{entity_id}/{ovn}` does work.

**Comment by BenjaminPelletier** [comment]
> But isn't [this](https://github.com/astm-utm/Protocol/blob/f6e5ee5a84cbe56d1b39187aa5ba0f67a7d8f5ec/utm.yaml#L2296) this a `DELETE` for `opreational_intent_references`? Moreover, based on the error [400 doc](https://github.com/astm-utm/Protocol/blob/f6e5ee5a84cbe56d1b39187aa5ba0f67a7d8f5ec/utm.yaml#L2315) shouldn't a missing `ovn` (which is a parameter) result in a `400`?

Yes, the DELETE is for [`/operational_intent_references/{entity_id}/{ovn}`](https://github.com/astm-utm/Protocol/blob/f6e5ee5a84cbe56d1b39187aa5ba0f67a7d8f5ec/utm.yaml#L2201).  https://example.com/dss/v1/operational_intent_references/f39b5d75-d2d5-43ab-b556-f1e696c1d367/asdf would resolve to this endpoint.  https://example.com/dss/v1/operational_intent_references/f39b5d75-d2d5-43ab-b556-f1e696c1d367/ should resolve to this endpoint with an empty OVN.  https://example.com/dss/v1/operational_intent_references/f39b5d75-d2d5-43ab-b556-f1e696c1d367 should resolve to the separate /operational_intent_references/{entity_id} endpoint which doesn't have a DELETE verb.

**Comment by svishnu-flyanra** [comment]
Ohh. Okay. That makes sense.
