### ISSUE TITLE
`state` field present in response for `operational_intent_references` 

### ISSUE THREAD

**Issue by svishnu-flyanra** [interuss/dss#577]
In the [`test_operation_simple.py`](https://github.com/interuss/dss/blob/73470c455c3bf3fc759d842c542743b8e8e116bb/monitoring/prober/scd/test_operation_simple.py#L246) file specifically `test_create_op_v15` after correcting the key name on line 239 from `operation_reference` to `operational_intent_reference` then test fails at state being present in the response. 

However, `state` is `''` (the empty string).

**Comment by BenjaminPelletier** [comment]
Did #571 fix this?  I'm not seeing it on the current scd_api_update branch

**Comment by svishnu-flyanra** [comment]
Yes it did. No more empty states.
