### ISSUE TITLE
Failures in test_operation_simple_heavy_traffic_concurrent.py

### ISSUE THREAD

**Issue by sjurcak** [interuss/dss#592]
**Describe the bug**

test_create_ops_concurrent:
Line 246: 'state' is now returned, so this line should be removed.

test_get_ops_by_ids_concurrent:
Line 274: 'state' is now returned, so this line should be removed.

test_get_ops_by_search_concurrent:
operational_intent_references are not stored or not returned. Possibly similar to issue #582

test_mutate_ops_concurrent:
Line 116: operational_intent_references PUT endpoint for update now requires an /ovn clause at the end of the URL. Will need to separate the create PUT request from the update PUT request, as the URLs are no longer the same. The ovn for the operation will need to be retrieved and included in the request
Line 339: 'state' is now returned, so this line should be removed.

test_delete_op_concurrent:
operational_intent_references DELETE endpoint now requires an /ovn clause at the end of the URL

**Comment by BenjaminPelletier** [comment]
Resolved by #599
