### ISSUE TITLE
Bug in introduction_to_repository.md

### ISSUE THREAD

**Issue by sjurcak** [interuss/dss#605]
**Describe the bug**

Line 19 in introduction_to_repository.md has a typo. 

- To run a DSS instance locally, see [this documentation](build/dev/stand_alone_instance.md).
Should be (remove the first _ from the linked filename)
- To run a DSS instance locally, see [this documentation](build/dev/standalone_instance.md).

**Comment by BenjaminPelletier** [comment]
Thanks!  Are you available to make a PR?

**Comment by sjurcak** [comment]
> Thanks! Are you available to make a PR?

I'm not able to make PRs I think.
