### ISSUE TITLE
Migrate from lib/pq to jackc/pgx

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/dss#616]
[The Postgres client we are using](https://github.com/lib/pq) is in maintenance mode and suggests that [pgx](https://github.com/jackc/pgx) is more actively developed.  We should migrate to the more actively-developed client.

See #467 for an old, un-merged PR that attempted to do this.

**Comment by pratibhagupta2109** [comment]
There are few concerns reported by other developers regarding the migration of` lib/pg` to` jackc/pgx `as listed in below mentioned comment and issue:
https://github.com/golang-migrate/migrate/issues/512#issuecomment-787008491
https://github.com/lib/pq/issues/1022

Please review if these are applicable to our migration too.

**Comment by BenjaminPelletier** [comment]
Those are both great links to know about.  On a cursory read, my guess is that the problems may have primarily stemmed from user error, but I'm definitely not sure.  To mitigate our risk, it would be great to do as little work as possible to get pgx working on enough of the DSS to allow us to benchmark its performance (and verify it doesn't have lots of errors).  I think a good performance benchmark will be one or more of our "heavy concurrent" tests -- we can (perhaps temporarily) add a couple lines to those tests to note the clock before the test starts and after it completes, then run the test ~5 times with pq then ~5 times with pgx and compare the performance.  If pgx performs at least, say, 90% as well as pq and doesn't have errors, then switching to a maintained (and recommended) project is probably a good strategy.  If we see errors or substantial performance problems, then we'll know to stick with pq.

**Comment by BenjaminPelletier** [comment]
Resolved by #679
