### ISSUE TITLE
Conformance/E2E tests

### ISSUE THREAD

**Issue by steeling** [interuss/dss#89]
We should add E2E conformance tests to validate code changes at the API level

**Comment by vosst** [comment]
@charlie-pisuraj @steeling with the tests being integrated into CI, do you think we can close out this ticket?

**Comment by charlie-pisuraj** [comment]
@vosst I'm still working on other parts of the conformance test that tests the interoperability the DSS, the plan is to spin up 2 copies of the DSS and run through a series of tests to ensure that both  work together properly

**Comment by charlie-pisuraj** [comment]
This was merged in to master, we can close this issue
