### ISSUE TITLE
Convert to Python 3

### ISSUE THREAD

**Issue by hi-kevin** [interuss/dss#9]
**Is your feature request related to a problem? Please describe.**
The current code is based on python 2.7. Eventually, this will become deprecated and we should move to Python 3.

**Describe the solution you'd like**
Upgrade the code and libraries to Python 3 and perform thorough testing.

**Comment by hrishiballal** [comment]
OK I have started a branch on my fork about this to do some testing. Some initial notes; 

Libraries: 
1) Kazoo is Python 3 compatible (I checked their repository and code, there are open bugs for testing with Py3) 
2) Flask is Python 3 
3) PyJWT is compatible (there is no mention of in-compatibility and they seem to have tests for Py3)

These are the external libraries that seem to be broadly compatible. I am going to test further.

**Comment by hrishiballal** [comment]
The code compiles and runs on Python 3. I have run a docker container for Zookeeper and running Flask locally. It seems to work no problems. I plan to look further.
