### ISSUE TITLE
Problem when pull/ clone the repo on windows

### ISSUE THREAD

**Issue by Dutzel** [interuss/dss#917]
**Describe the bug**
Its currently not possible to clone or pull from the repo on windows.

The log shows: 

`git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks fetch --no-tags origin

git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks pull --rebase origin master
From https://github.com/interuss/dss
 * branch            master     -> FETCH_HEAD

error: The following untracked working tree files would be overwritten by merge:
	interfaces/aux_/aux.yaml
Please move or remove them before you merge.
Aborting
Updating e5bf429..ed87121
`

**To Reproduce**
1. pull the repo

**Expected behavior**
Repo should be pulled.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11

**Comment by mickmis** [comment]
Have you tried doing a clean clone from scratch?
If you kept the repo after pulling in the new `aux` now removed with #914, I do not think git will handle this well because Windows probably hides the folder from all processes.
So I would expect that pulling the latest commits is unfortunately not enough to recover.

**Comment by Dutzel** [comment]
Hey mickmis, 
thank you very much for taking this issue. 
Now normal clowning works, but the cloned repo contains several problems (see picture 1)

![image](https://user-images.githubusercontent.com/17947422/205915138-03f4ce0f-afc2-403a-8d9d-6d4d77ffcd6e.png)

There are still invalid paths (e.g. "interfaces/aux_/aux.yaml"). If I then try to delete it via the git shell, the same error as in my git tool snippet below is displayed.

![image](https://user-images.githubusercontent.com/17947422/205915919-aba9cc6b-9beb-4e29-8256-d637f02391b9.png)

**Comment by mickmis** [comment]
Indeed, I believed only folders would be an issue, but files named `aux` with any extension also are problematic.
In PR #918 we fix this and ensure the problem does not arise again through automatic checks.

**Comment by barroco** [comment]
PR #918 has been merged and should fix the issue. @Dutzel, please comment on this issue if you still experience problems.

**Comment by Dutzel** [comment]
Thank you very much :) Pulling works now
