### ISSUE TITLE
Links to F3411 API within README.md are broken

### ISSUE THREAD

**Issue by arushton** [interuss/dss#956]
README.md

-> [F3411-19 OpenAPI interface](https://github.com/interuss/dss/blob/master/interfaces/rid/v1/remoteid) 
-> [F3411-22 OpenAPI interface](https://github.com/interuss/dss/blob/master/interfaces/rid/v2/remoteid)

Please provide updated links

**Comment by BenjaminPelletier** [comment]
These links are valid when submodules are initialized, but GitHub [apparently does not resolve links into submodules](https://stackoverflow.com/questions/44333322/how-to-add-a-relative-link-to-a-file-in-a-submodule-in-github-markdown).  We'll have to think about how to address this as an explicit link would need to be manually updated whenever the submodule reference was changed, and it seems likely this may drift out of sync over time.

In the mean time, the subrepo links can be seen [here](https://github.com/interuss/dss/tree/master/interfaces/rid).

**Comment by nasajoey** [comment]
Recommend closing based on #970 .
